[build]
dist = "../frontend/game"
public_url = "/game"
release = true     # (opcional) siempre build --release
filehash = false   # (opcional) si no quieres hashes

[[copy]]
source = "assets"
dest   = "assets"
ignore = ["*.meta"]
