[build]
dist = "../rustball_backend/webapp/game"  # <-- carpeta que ya sirves con Axum
public_url = "/game"
release = true     # (opcional) siempre build --release
filehash = false   # (opcional) si no quieres hashes

[[copy]]
source = "assets"
dest   = "assets"
ignore = ["*.meta"]

[[copy]]
source = "bootstrap.js"
dest = "bootstrap.js"
